### ISSUE TITLE
What's the difference between this and cms.databaseTemplates?

### ISSUE THREAD

**Issue by LukeTowers** [Balex70/dynopages#1]
What is the difference between this plugin's functionality and the recently released `cms.databaseTemplates` config option merged in https://github.com/octobercms/october/pull/3908?

**Comment by Balex70** [comment]
Hi @LukeTowers,
As I see cms.databaseTemplates feature now on develop branch. Actually, I have started working on this plugin more than half a year ago. Between working on client's project we were able to test the plugin and avoid losing content that client added, using master branch of OctoberCMS and RainLab.Pages.
I'm sure that "Database layer for the CMS objects" will be a great feature and I would like to have native DB support it as soon as possible on production.

**Comment by LukeTowers** [comment]
Build 457 fixes a lot of bugs so once we launch it (probably in the next two weeks) and have it sit for a week without issues it and 456 will go stable. So the database layer should be available within a month on master.

**Comment by LukeTowers** [comment]
This repo is still a valuable resource as a code example for people looking to do something similar, but if you keep the plugin active on the marketplace I would ask you to put a big notice in the description that people should try using the native feature instead.

**Comment by Balex70** [comment]
Sure, let me know when I should do that, I guess after database layer will be on master.

**Comment by LukeTowers** [comment]
@Balex70 this feature has been in the core now for over half a year, sorry for the delayed update. See https://github.com/octobercms/october/blob/master/config/cms.php#L229-L253, https://github.com/octobercms/docs/blob/master/cms-themes.md#database-driven-themes, & https://github.com/octobercms/docs/blob/master/console-commands.md#theme-sync-command

**Comment by Balex70** [comment]
@LukeTowers Thanks, I have updated the README

**Comment by LukeTowers** [comment]
@Balex70 Could you add the following to the top of your plugin page in the marketplace:
```md
> **IMPORTANT**: Though we continue to support this project, we strongly recommend using the built-in October CMS feature called ["Database Driven Themes"](https://github.com/octobercms/docs/blob/master/cms-themes.md#database-driven-themes) and the 
 [`theme:sync` console command](https://github.com/octobercms/docs/blob/master/console-commands.md#theme-sync-command)
```

**Comment by Balex70** [comment]
Done

**Comment by LukeTowers** [comment]
Perfect, thanks!
